### ISSUE TITLE
Can't install using NodeJS' snap

### ISSUE THREAD

**Issue by NatoBoram** [nwjs/npm-installer#73]
### Versions
```
node --version
v11.14.0
npm --version
6.9.0
```

### Operating System
```yaml
OS: Ubuntu 18.04.2 LTS x86_64 
Kernel: 4.15.0-48-generic 
Uptime: 23 hours, 45 mins 
Packages: 2578 
Shell: bash 4.4.19 
Resolution: 1920x1080, 1920x1080, 1920x1080 
DE: Unity 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: vscode 
CPU: AMD Ryzen 3 1200 (4) @ 3.100GHz 
GPU: NVIDIA GeForce GTX 1050 
Memory: 5060MiB / 16039MiB 
```

### Error
```bash
sudo npm i -g nw
/usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/1935/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> nw@0.37.4 postinstall /usr/local/lib/node_modules/nw
> node scripts/install.js

2019/04/17 16:08:17.508260 cmd_run.go:876: WARNING: cannot create user data directory: cannot create "/nonexistent/snap/node/1935": mkdir /nonexistent: permission denied
cannot create user data directory: /nonexistent/snap/node/1935: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nw@0.37.4 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.37.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/natoboram/.npm/_logs/2019-04-17T20_08_17_611Z-debug.log
```
